AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    usage-data-collector-app
Globals:
    Function:
        Timeout: 3

Resources:
    AcceptUsageDataFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: app.lambda_handler
            Runtime: nodejs8.10
            Environment:
                Variables:
                    PARAM1: VALUE
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /usagedata
                        Method: post

Outputs:
    AcceptUsageDataApi:
      Description: "API Gateway endpoint URL for Prod stage for AcceptUsageDataFunction function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/usagedata/"

    AcceptUsageDataFunction:
      Description: "AcceptUsageDataFunction Lambda Function ARN"
      Value: !GetAtt AcceptUsageDataFunction.Arn

    AcceptUsageDataFunctionIamRole:
      Description: "Implicit IAM Role created for AcceptUsageDataFunction function"
      Value: !GetAtt AcceptUsageDataFunctionRole.Arn
